# Generated by Django 2.0.9 on 2018-12-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_empleado_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cliente',
        ),
        migrations.AddField(
            model_name='empleado',
            name='cliente',
            field=models.ManyToManyField(to='blog.Cliente'),
        ),
    ]
